language: node_js
node_js:
  - '10'
  - '11'

services:
  - docker

before_install:
  - docker build -t rabbitmq:official-alpine-with-webstomp rabbitmq/
  - docker run -d --hostname rabbitmq --name rabbitmq -p 15674:15674 rabbitmq:official-alpine-with-webstomp

before_script:
  - docker exec rabbitmq rabbitmqctl status

script:
  - bin/ci.sh
  - bin/rx-stomp.sh
  - bin/ng2-stompjs.sh
